INSERT INTO books (name, author, year, masterpiece) VALUES
('Cien años de soledad',              'Gabriel García Márquez',         1967, false),
('O Alquimista',                      'Paulo Coelho',                   1988, false),
('Don Quijote de la Mancha',          'Miguel de Cervantes',            1605, false),
('Ensaio Sobre a Cegueira',           'José Saramago',                  1995, false),
('The Great Gatsby',                  'F. Scott Fitzgerald',            1925, false),
('Ficciones',                         'Jorge Luis Borges',              1944, false),
('O Primo Basílio',                   'José Maria de Eça de Queirós',   1878, false),
('Rayuela',                           'Julio Cortázar',                 1963, false),
('1984',                              'George Orwell',                  1949, false),
('Dom Casmurro',                      'Machado de Assis',               1899, false),
('Pedro Páramo',                      'Juan Rulfo',                     1955, false),
('Capitães da Areia',                 'Jorge Amado',                    1937, false),
('Ulysses',                           'James Joyce',                    1922, false),
('La ciudad y los perros',            'Mario Vargas Llosa',             1963, false),
('A Hora da Estrela',                 'Clarice Lispector',              1977, false),
('To Kill a Mockingbird',             'Harper Lee',                     1960, false),
('Crónica de una muerte anunciada',   'Gabriel García Márquez',         1981, false),
('Grande Sertão: Veredas',            'João Guimarães Rosa',            1956, false),
('Brave New World',                   'Aldous Huxley',                  1932, false),
('Como agua para chocolate',          'Laura Esquivel',                 1989, false),
('Memorial do Convento',              'José Saramago',                  1982, false),
('The Catcher in the Rye',            'J.D. Salinger',                  1951, false),
('La sombra del viento',              'Carlos Ruiz Zafón',              2001, false),
('Memórias Póstumas de Brás Cubas',   'Machado de Assis',               1881, false),
('Crime and Punishment',              'Fyodor Dostoevsky',              1866, false),
('El túnel',                          'Ernesto Sabato',                 1948, false),
('O Cortiço',                         'Aluísio Azevedo',                1890, false),
('Pride and Prejudice',               'Jane Austen',                    1813, false),
('2666',                              'Roberto Bolaño',                 2004, false),
('O Guarani',                         'José de Alencar',                1857, false),
('War and Peace',                     'Leo Tolstoy',                    1869, false),
('Los pasos perdidos',                'Alejo Carpentier',               1953, false),
('Vidas Secas',                       'Graciliano Ramos',               1938, false),
('The Old Man and the Sea',           'Ernest Hemingway',               1952, false),
('Santa Evita',                       'Tomás Eloy Martínez',            1995, false),
('Quincas Borba',                     'Machado de Assis',               1891, false),
('One Flew Over the Cuckoo''s Nest',  'Ken Kesey',                      1962, false),
('La tregua',                         'Mario Benedetti',                1960, false),
('Auto da Barca do Inferno',          'Gil Vicente',                    1517, false),
('The Stranger',                      'Albert Camus',                   1942, false),
('El Aleph',                          'Jorge Luis Borges',              1949, false),
('Tieta do Agreste',                  'Jorge Amado',                    1977, false),
('Jane Eyre',                         'Charlotte Brontë',               1847, false),
('Doña Bárbara',                      'Rómulo Gallegos',                1929, false),
('Os Maias',                          'José Maria de Eça de Queirós',   1888, false),
('Moby-Dick',                         'Herman Melville',                1851, false),
('Aura',                              'Carlos Fuentes',                 1962, false),
('Menino do Engenho',                 'José Lins do Rego',              1932, false),
('Fahrenheit 451',                    'Ray Bradbury',                   1953, false),
('El amor en los tiempos del cólera', 'Gabriel García Márquez',         1985, false),
('The Lord of the Rings',             'J.R.R. Tolkien',                 1954, false),
('La colmena',                        'Camilo José Cela',               1951, false),
('Iracema',                           'José de Alencar',                1865, false),
('Wuthering Heights',                 'Emily Brontë',                   1847, false),
('La muerte de Artemio Cruz',         'Carlos Fuentes',                 1962, false),
('São Bernardo',                      'Graciliano Ramos',               1934, false),
('The Metamorphosis',                 'Franz Kafka',                    1915, false),
('Sobre héroes y tumbas',             'Ernesto Sabato',                 1961, false),
('O Alienista',                       'Machado de Assis',               1882, false),
('Lolita',                            'Vladimir Nabokov',               1955, false),
('La fiesta del Chivo',               'Mario Vargas Llosa',             2000, false),
('Gabriela, Cravo e Canela',          'Jorge Amado',                    1958, false),
('The Picture of Dorian Gray',        'Oscar Wilde',                    1890, false),
('Los detectives salvajes',           'Roberto Bolaño',                 1998, false),
('O Ateneu',                          'Raul Pompeia',                   1888, false),
('Frankenstein',                      'Mary Shelley',                   1818, false),
('Claro Enigma',                      'Carlos Drummond de Andrade',     1951, false),
('The Brothers Karamazov',            'Fyodor Dostoevsky',              1880, false),
('Bom-Crioulo',                       'Adolfo Caminha',                 1895, false),
('In Search of Lost Time',            'Marcel Proust',                  1913, false),
('Relato de un náufrago',             'Gabriel García Márquez',         1955, false),
('Lucíola',                           'José de Alencar',                1862, false),
('The Alchemist',                     'Paulo Coelho',                   1988, false),
('Niebla',                            'Miguel de Unamuno',              1914, false),
('Mayombe',                           'Pepetela',                       1980, false),
('Madame Bovary',                     'Gustave Flaubert',               1856, false),
('Terra Nostra',                      'Carlos Fuentes',                 1975, false),
('O Tempo e o Vento',                 'Erico Verissimo',                1949, false),
('Great Expectations',                'Charles Dickens',                1861, false),
('Pantaleón y las visitadoras',       'Mario Vargas Llosa',             1973, false),
('A Relíquia',                        'Eça de Queirós',                 1887, false),
('Catch-22',                          'Joseph Heller',                  1961, false),
('El siglo de las luces',             'Alejo Carpentier',               1962, false),
('O Continente',                      'Erico Verissimo',                1949, false),
('Don Juan Tenorio',                  'José Zorrilla',                  1844, false),
('Anna Karenina',                     'Leo Tolstoy',                    1877, false),
('La vida es sueño',                  'Pedro Calderón de la Barca',     1635, false),
('Os Lusiadas',                       'Luís de Camões',                 1572, false),
('The Grapes of Wrath',               'John Steinbeck',                 1939, false),
('Soldados de Salamina',              'Javier Cercas',                  2001, false),
('Sagarana',                          'João Guimarães Rosa',            1946, false),
('Animal Farm',                       'George Orwell',                  1945, false),
('El señor presidente',               'Miguel Ángel Asturias',          1946, false),
('A Paixão Segundo G.H.',             'Clarice Lispector',              1964, false),
('The Trial',                         'Franz Kafka',                    1925, false),
('Doce cuentos peregrinos',           'Gabriel García Márquez',         1992, false),
('Dona Flor e Seus Dois Maridos',     'Jorge Amado',                    1966, false),
('La familia de Pascual Duarte',      'Camilo José Cela',               1942, false),
('Felicidade Clandestina',            'Clarice Lispector',              1971, false),
('Dracula',                           'Bram Stoker',                    1897, false),
('Cari Mora',                         'Thomas Harris',                  2019, false);
